//Login
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";

//Payment
export const TRANSACTION_SUCCESS = "TRANSACTION_SUCCESS";
export const TRANSACTION_FAILED = "TRANSACTION_FAILED";

//Image upload
export const UPLOAD_PROGRESS = "UPLOAD_PROGRESS";
export const UPLOAD_ERROR = "UPLOAD_ERROR";
export const GET_DOWNLOAD_URL = "GET_DOWNLOAD_URL";
//Category selection
export const CATEGORY_SELECTED = "CATEGORY_SELECTED";
//Errors
export const CREATE_ERROR = "CREATE_ERROR";
export const FETCH_ERROR = "FETCH_ERROR";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";
export const GOOGLE_SIGNIN_ERROR = "GOOGLE_SIGNIN_ERROR";

export const SET_LOADER = "SET_LOADER";

export const COMPLETE_USER_DATA = "COMPLETE_USER_DATA";
export const FETCH_CURRENT_USER = "FETCH_CURRENT_USER";

export const CREATE_BUSINESS = "CREATE_BUSINESS";
export const FETCH_BUSINESSES = "FETCH_BUSINESSES";
export const FETCH_SELECTED_BUSINESS = "FETCH_SELECTED_BUSINESS";
export const FETCH_BUSINESS_PARTNERS_EXPERIENCES =
  "FETCH_BUSINESS_PARTNERS_EXPERIENCES";

export const SEARCH_BUSINESS_OWNER = "SEARCH_BUSINESS_OWNER";
export const EDIT_BUSINESS = "EDIT_BUSINESS";
export const DELETE_BUSINESS = "DELETE_BUSINESS";

export const CREATE_EXPERIENCE = "CREATE_EXPERIENCE";
export const FETCH_USER_EXPERIENCES = "FETCH_USER_EXPERIENCES";
export const FETCH_PUBLISHED_EXPERIENCES =
  "FETCH_PUBLISHED_EXPERIENCES";
export const FETCH_EXPERIENCE = "FETCH_EXPERIENCE";
export const FETCH_SELECTED_BIZ_EXPERIENCES =
  "FETCH_SELECTED_BIZ_EXPERIENCES";

export const EDIT_EXPERIENCE = "EDIT_EXPERIENCE";
export const DELETE_EXPERIENCE = "DELETE_EXPERIENCE";
export const EXPERIENCE_SELECTED = "EXPERIENCE_SELECTED";
export const FETCH_PARTNERS_EXPERIENCES =
  "FETCH_PARTNERS_EXPERIENCES";
